### ISSUE TITLE
Review license choice

### ISSUE THREAD

**Issue by Luming-ubc** [UBC-MDS/pyeasyeda#68]
review your projects’ license choice (and change it if you deem it is warranted).

**Comment by Luming-ubc** [comment]
Instructions: "Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice by opening issues in both Python and R repositories. As it is likely to be a very similar discussion for both projects, one of these issues can just link to the other issue where it is thoroughly dicussed."

**Comment by jamesktkim** [comment]
I suggest we stick to MIT License for the following reasons: 

- We are not working in a community so there is no need to ask the community about the license usage
- MIT is a license that is very commonly used and free, which makes life easier for both contributors and users
- Given the scope and purpose of our project, our license can be simple and permissive 
- Our project goal aligns with the following permissions - commercial use, distribution, modification, private use
- Under MIT we will not be liable for any harm caused by using our work
- We can consider adding creative commons license but not strongly required given the scope of our work

**Comment by sukhleen999** [comment]
I agree with James on the choice of license. As highlighted by him, the MIT license would be a good fit for our project since it is friendly to both businesses and open-source developers (in addition to other advantages).

**Comment by khbunyan** [comment]
Hi all, thanks for the write up James. I agree with all of your notes and that the MIT license is the best choice for our packages.

**Comment by Luming-ubc** [comment]
I agree with your choice. This is the website that provides options for our license choice. [link](https://choosealicense.com/) I think MIT license is suitable in our case because it is simple and permissive. Like James mentioned, we don't have a preferred community and in fact we welcome other people to review, test, and use our source code in their applications. The purpose of creating this project is mainly for learning and sharing, and we have no issue with other's making and distributing closed source versions based on our project.
